replicaCount: 1

image:
  repository: deployments-calendar
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80 #hostPort: 8055 # it works for extraPortMappings in `kind-example-config.yaml`
  # type: NodePort ##another mode :  to expose the service
  # port: 8081
  # nodePort: 30090

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix

calendarConfig:
  loggerLevel: "info" # info or error
  httpListen: ":8081"
  httpPort: 8081
  grpcListen: ":50051"
  grpcPort: 50051
  storageType: "postgres" # "memory"  or  "postgres"
  postgresDsn: "host=postgres port=5432 user=otus_user1 password=otus_password1 dbname=events sslmode=disable" #migration = "migrations"
  migrationsPath: "./migrations"          

producer:
  enabled: true
  replicaCount: 1
  image:
    repository: deployments-producer
    tag: "latest"
    pullPolicy: IfNotPresent
  containerPort: 8082
  service:
    type: ClusterIP
    port: 8082
  ingress:
    enabled: false

consumer:
  enabled: true
  replicaCount: 1
  image:
    repository: deployments-consumer
    tag: "latest"
    pullPolicy: IfNotPresent
  containerPort: 8083
  service:
    type: ClusterIP
    port: 8083
  ingress:
    enabled: false

rabbitmq:
  hostAlias:
    enabled: false
    ip: "10.43.90.29"
    hostname: "my_rabbitmq" # not working as per DNS convention

hostAliases:
  enabled: false