logger:
  level: "info" # info or error

http:
  listen: ":8081"

storage:
  type: "postgres" # "memory"  or  "postgres"
  postgres:
    dsn: "_use_ENV_" #migration = "migrations"

migrationsPath: "./migrations"