logger:
  level: "info" # info or error

http:
  listen: ":8081"

storage:
  type: "postgres" # "memory"  or  "postgres"
  postgres:
    dsn: "host=acs_modx303.cozymods.com user=otus_user1 password=otus_password1 dbname=events sslmode=disable" #migration = "migrations"

migrationsPath: "./migrations"