logger:
  level: "info" # info or error

http:
  listen: ":8081"

grpc:
  listenGrpc: ":50051"

storage:
  type: "postgres" # "memory"  or  "postgres"
  postgres:
    dsn: "host=events-postgres port=5432 user=otus_user1 password=otus_password1 dbname=events sslmode=disable" #migration = "migrations"

migrationsPath: "./migrations"