logger:
  level: "info" # info or error

http:
  listen: ":8081"

grpc:
  listenGrpc: ":50051"

storage:
  type: "memory" # "memory"  or  "postgres"
  postgres:
    dsn: "host=-----" #migration = "migrations"

migrationsPath: "./migrations"