user: "guest"
password: "guest"
host: "my-rabbitmq"         #AMQP URI host (no underscores to follow k8s hostnaming conventions)
port: "5672"
exchange: "test-exchange" #Durable, non-auto-deleted AMQP exchange name
exchangeType: "direct"   #Exchange type - direct|fanout|topic|x-custom")
queue: "test-queue"       #Ephemeral AMQP queue name
key: "test-key"           #AMQP binding key
consumerTag: "simple-consumer"  #AMQP consumer tag (should not be blank)
lifetime: 0               #lifetime of process before shutdown (0s=infinite)