rabbit:
  user: "guest"
  password: "guest"
  host: "my-rabbitmq"         #AMQP URI host (no underscores to follow k8s hostnaming conventions)
  port: "5672"
  exchange: "test-exchange" #Durable, non-auto-deleted AMQP exchange name
  exchangeType: "direct"   #Exchange type - direct|fanout|topic|x-custom")
  queue: "test-queue"       #Ephemeral AMQP queue name
  key: "test-key"           #AMQP binding key
  consumerTag: "simple-consumer"  #AMQP consumer tag (should not be blank)
  sync: true                      #Use synchronous confirms example

config:
  storage:
    type: "postgres"
    postgres:
      dsn: "host=events-postgres port=5432 user=otus_user1 password=otus_password1 dbname=events sslmode=disable" #migration = "migrations"
  migrationsPath: "./migrations"
